db:
  image: postgres
  restart: always
  expose:
    - "5432"

web:
  build: .
  restart: always
  command: bash -c "rm -v /myapp/tmp/pids/server.pid ; bundle install && bin/rails server --port 3000 --binding 0.0.0.0"
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db:db
